// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF8J_HXO52798FcRamg1lN6I7CLT09u8o',
    appId: '1:240557053604:web:b98bab21fa4c972eac7831',
    messagingSenderId: '240557053604',
    projectId: 'instaapp-clone-flutter',
    authDomain: 'instaapp-clone-flutter.firebaseapp.com',
    storageBucket: 'instaapp-clone-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnmHIHMzZ9CGDxVGm3YYjIRSlMKSiMB10',
    appId: '1:240557053604:android:b8137469173b780bac7831',
    messagingSenderId: '240557053604',
    projectId: 'instaapp-clone-flutter',
    storageBucket: 'instaapp-clone-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO6Gae77nAkyhKsJIhPFNN4Cdbis7kz0c',
    appId: '1:240557053604:ios:030a80b8983975b6ac7831',
    messagingSenderId: '240557053604',
    projectId: 'instaapp-clone-flutter',
    storageBucket: 'instaapp-clone-flutter.appspot.com',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO6Gae77nAkyhKsJIhPFNN4Cdbis7kz0c',
    appId: '1:240557053604:ios:66e12d2cc506ef34ac7831',
    messagingSenderId: '240557053604',
    projectId: 'instaapp-clone-flutter',
    storageBucket: 'instaapp-clone-flutter.appspot.com',
    iosBundleId: 'com.example.instagramFlutter.RunnerTests',
  );
}
